INSERT INTO CUSTOMER VALUES(1,'Steven','Haines','steve@javasrc.com','steve')

INSERT INTO CATEGORY VALUES(1,'Fruit')

INSERT INTO CATEGORY VALUES(2,'Vegetables')

INSERT INTO CATEGORY VALUES(3,'Meat')

INSERT INTO CATEGORY VALUES(4,'Dairy')

INSERT INTO CATEGORY VALUES(5,'Organic')

INSERT INTO PRODUCT VALUES(1,'Apple',0.25E0,'Food',10)

INSERT INTO PRODUCT VALUES(2,'Orange',0.5E0,'Food',10)

INSERT INTO PRODUCT VALUES(3,'Banana',0.75E0,'Food',0)

INSERT INTO PRODUCT VALUES(4,'Peas',1.5E0,'Food',10)

INSERT INTO PRODUCT VALUES(5,'Carrots',1.0E0,'Food',10)

INSERT INTO PRODUCT VALUES(6,'Organic Apple',0.75E0,'Food',10)

INSERT INTO PRODUCT_CATEGORIES VALUES(1,1)

INSERT INTO PRODUCT_CATEGORIES VALUES(2,1)

INSERT INTO PRODUCT_CATEGORIES VALUES(3,1)

INSERT INTO PRODUCT_CATEGORIES VALUES(4,2)

INSERT INTO PRODUCT_CATEGORIES VALUES(5,2)

INSERT INTO PRODUCT_CATEGORIES VALUES(6,1)

INSERT INTO PRODUCT_CATEGORIES VALUES(6,5)